version: '3'

services:
  app:
    image: pvrmza/docker-phpipam
    env_file:
      - .env_phpipam
    depends_on:
      - db
    ports:
      - 9865:80
    links:
      - db 

  db:
    image: mariadb:latest
    env_file:
      - .env_phpipamdb
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql

volumes:
  phpipam-db-data:
